### PR TITLE
Beta 50 week 1

### PR DESCRIPTION
**Pull request by dzeber**
Adding analysis notebook for Beta 50 week 1.

This version fixes the two broken histogram analyses, and adds tables of top add-ons.

### CODE REVIEW

**Comment by chutten** [comment]
Which two broken histogram analyses were those?

**Comment by chutten** [comment]
Hrm. On In[54], the print line doesn't show up in the output like it does in In[53] below it.

**Comment by dzeber** [comment]
The broken histograms were `FX_TAB_SWITCH_TOTAL_MS` and the plugin jank ones as discussed in #53.

> On In[54], the print line doesn't show up in the output like it does in In[53] below it.
That's probably from moving code around and not rerunning the cell. I'll have to rerun the notebook.

**Comment by dzeber** [comment]
I reran the notebook, which fixed the missing add-ons count line from the previous In[54].

**Comment by chutten** [comment]
LGTM

**Pull request merged**
