### PR TITLE
Adding analysis notebooks for Beta 49 e10s add-ons experiments

### PR DESCRIPTION
**Pull request by dzeber**
I've created a notebook template for the analyzing the results from the Beta 49 experiment assessing e10s performance in the presence of add-ons. The notebook is based on the one for Beta 48, with some changes to metrics and information displayed.

So far, this includes results for weeks 1-3 of the experiment. I'll continue running it for the next couple of weeks and will push future notebooks to this branch.

### CODE REVIEW

**Comment by chutten** [comment]
Looking at `week1/e10s_experiment.ipynb`

For `In[108] `, the hgrams `"payload/histograms/BLOCKED_ON_PLUGIN_MODULE_INIT_MS", "payload/histograms/BLOCKED_ON_PLUGIN_INSTANCE_INIT_MS", "payload/histograms/BLOCKED_ON_PLUGIN_INSTANCE_DESTROY_MS"` are keyed histograms, so they'd be under `payload/keyedHistograms` ...but you can probably just remove them. The distributions will be of low counts against the already-small cohorts, so I don't know that we'll be able to make a meaningful comparison of even the most popular plugins.

I love that `MEMORY_TOTAL` shows that addons correlates with higher memory consumption. Nice validation of experimental design, there. Reading that finding off of the diff-of-diff plot is kinda hard for my brain to figure out, though. It's like trying to look at acceleration plots to figure out which car is further down the track.

`FX_TAB_SWITCH_TOTAL_MS` is absent in e10s profiles? ...really? \*checks\* Ohhh, the e10s data was split off to `FX_TAB_SWITCH_TOTAL_E10S_MS`. That was unhelpful of whoever added those probes. If you have some cycles to spare, compare and contrast between the two of them. Until then, maybe post a note inline so we know what's up.

Looking at `week1/e10s_experiment_old.ipynb`: is there a reason you're keeping this around? Looks like something we could omit.

I gave a couple of quick scans at `week2` and `week3`. They seem very similar (excepting the dates), which is pretty much what we're hoping for.

**Comment by dzeber** [comment]
> For In[108], the hgrams "payload/histograms/BLOCKED_ON_PLUGIN_MODULE_INIT_MS", "payload/histograms/BLOCKED_ON_PLUGIN_INSTANCE_INIT_MS", "payload/histograms/BLOCKED_ON_PLUGIN_INSTANCE_DESTROY_MS" are keyed histograms, so they'd be under payload/keyedHistograms ...but you can probably just remove them. 

Fair enough. What I could do is include them (with the right path) in the run for week 4, just to see what they look like, and exclude them from future weeks.

> I love that MEMORY_TOTAL shows that addons correlates with higher memory consumption. Reading that finding off of the diff-of-diff plot is kinda hard for my brain to figure out, though.

Yes, the diff-in-diff plot is not very helpful for this one, but at least we can see what's going on from the other two plots. Not only does memory consumption increase in the presence of add-ons, but it looks like switching on e10s causes the distribution to become bimodal. I like how MEMORY_VSIZE_MAX_CONTIGUOUS shows those spikes when add-ons are present (probably specific add-ons with specific memory consumption patterns).

> FX_TAB_SWITCH_TOTAL_MS is absent in e10s profiles? ...really? *checks* Ohhh, the e10s data was split off to FX_TAB_SWITCH_TOTAL_E10S_MS. If you have some cycles to spare, compare and contrast between the two of them. Until then, maybe post a note inline so we know what's up.

I'll do that. So I should compare FX_TAB_SWITCH_TOTAL_MS for non-e10s cohorts to FX_TAB_SWITCH_TOTAL_E10S_MS for e10s cohorts?

> Looking at week1/e10s_experiment_old.ipynb: is there a reason you're keeping this around?

No, not really. I'll remove it.

> I gave a couple of quick scans at week2 and week3. They seem very similar (excepting the dates), which is pretty much what we're hoping for.

Yes, I basically copied the entire notebook and reran it on the appropriate derived dataset.

**Comment by dzeber** [comment]
Also, I've added a text-based JSON-like representation of the re:dash queries used to track stability metrics under beta/49/stability-metrics-redash/. That way those queries and visualizations can be version-controlled in the same place.

**Comment by chutten** [comment]
> [re: BLOCKED_ON_PLUGIN_INIT et al] What I could do is include them (with the right path) in the run for week 4, just to see what they look like, and exclude them from future weeks.

If you go for it, focus on whatever the most popular plugin+version is (some version of Flash, almost certainly). You can path straight to a given key for a keyedHistogram like so `"payload/keyedHistograms/BLOCKED_ON_PLUGIN_INSTANCE_DESTROY_MS/Shockwave Flash21.0.0.242"`

> So I should compare FX_TAB_SWITCH_TOTAL_MS for non-e10s cohorts to FX_TAB_SWITCH_TOTAL_E10S_MS for e10s cohorts?

Correct.

The stability dashboard looks like it's covering the corners nicely. I'll review in more detail in [bug 1295291](https://bugzilla.mozilla.org/show_bug.cgi?id=1295291).

**Pull request merged**
